### ISSUE TITLE
User/permission objects & API Requests

### ISSUE THREAD

**Issue by hampsterx** [kristovaher/Wave-Framework#11]
user data is backed by session so this cannot be used for API requests.

"Wave Framework holds user data in sessions. Technically you should build a local Database or load user data from an external database with a Controller that you develop for your system. Wave Framework doesn't come with a user database and login systems from the get go and only has a session storage set up for supporting such systems."

Quite happy to build my own user/login system but would be nice if I could use the "user" and "permission" concepts for both web and api requests and or avoid having to hit the database to validate every API call.

Any suggestions appreciated.

**Comment by TomerW** [comment]
On a simpler note, How can I in a controller method know the 'logged-in' profile info?
