### ISSUE TITLE
Can't Access tools directory

### ISSUE THREAD

**Issue by eudosia** [kristovaher/Wave-Framework#161]
Installed  latest stable code. Changed User name and password (in config.ini) for tools directory, but seems like credentials are wrong. I have apache and fastcgi vhost configured
<VirtualHost xxx.xxx.xxx.xxx:80>
ServerName xxxxxxxx
   #ServerAlias web1
   ServerAdmin webmaster@localhost
DocumentRoot /var/www/vhosts/api/httpdocs/
   <IfModule mod_fcgid.c>
      SuexecUserGroup api api
      #PHP_Fix_Pathinfo_Enable 1
      <Directory /var/www/vhosts/api/httpdocs/>
                Options +ExecCGI
                AllowOverride All
                AddHandler fcgid-script .php
                FCGIWrapper /var/www/fcgi/api/fcgi .php
                Order allow,deny
                Allow from all
            </Directory>
        </IfModule>
         ErrorLog /var/www/vhosts/api/log/error.log
         CustomLog /var/www/vhosts/api/log/access.log combined
        # ServerSignature Off
</VirtualHost>
I have copied .htaccess files...
Any idea ?
Thank you

**Comment by BoumPower** [comment]
Hi
I have the same problem (OVH hosting)
Thanks for help....

**Comment by kristovaher** [comment]
Sadly this repository hasn't been actively maintained for a handful of years. I did test it on a public VM service running PHP 8.1 and Apache 2 and had no problems. Note that the /tools/ folder has its own .htaccess file and has to be in the right folder. Apache requires "AllowOverride" setting to be on for that to work. From the readme: "Apache also needs to support '.htaccess' directives from those files, so make sure that 'AllowOverride' setting is 'All' in Apache directory configuration. This is usually enabled by default on most servers."
